language: ruby
rvm:
  - 2.2.2
before_install:
  - "export DISPLAY=:99.0"
  - "export CODECLIMATE_REPO_TOKEN=1e8a50c722cf9e8372e479379bb14dbb1a224f25e260cbde22aae4768a237e07"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "bundle exec rake test_app"
script:
  - "bundle exec rubocop"
  - "bundle exec rake"
notifications:
  email:
    - seb@madetech.co.uk
